version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      jenkins: {}
    ports:
      - "8080:8080"
volumes:
  jenkins_home:
networks:
  jenkins:
    external: true